services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    restart: always
    command: start-dev --import-realm
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: pass
    volumes:
      - ./realms:/opt/keycloak/data/import
    depends_on:
      - postgres
    networks:
      - backend


networks:
  backend:
    driver: bridge



#   config-service:
#     image: atef/config-service:1.0
#     container_name: config-service-container
#     build: config-service
#     ports:
#       - "8888:8888"
#     restart: on-failure
#     volumes:
#       - ./config-service
#
#   discovery-service:
#     image: atef/discovery-service:1.0
#     container_name: discovery-service
#     build: discovery-service
#     restart: on-failure
#     ports:
#       - "8761:8761"
#     volumes:
#       - ./discovery-service
#
#   gateway-service:
#     image: atef/gateway-service:1.0
#     container_name: gateway-service
#     build: gateway-service
#     restart: on-failure
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./gateway-service
#
#
#   stock-ms:
#     image: atef/stock-ms:1.0
#     container_name: stock-ms
#     build: supervise-service
#     restart: on-failure
#     ports:
#       - "9091:9091"
#     volumes:
#       - ./stock-ms
#
#
#   product-ms:
#     image: atef/product-ms:1.0
#     container_name: product-ms
#     build: pillbox-service
#     restart: on-failure
#     ports:
#       - "9092:9092"
#     volumes:
#       - ./product-ms
