services:
  # Include postgres explicitly here again
  # docker-compose -f infrastructure/mongo/infra-compose.yml -f keycloak-compose.yml up --build
  postgres:
    extends:
      file: ./infrastructure/mongo/infra-compose.yml
      service: postgres

  keycloak:
    extends:
      file: keycloak-compose.yml
      service: keycloak
