services:
  postgres:
    extends:
      file: ./infrastructure/mongo/infra-compose.yml
      service: infrastructure

  keycloak:
    extends:
      file: keycloak-compose.yml
      service: keycloak

  kafka:
    extends:
      file: kafka-compose.yml
      service: kafka

  zookeeper:
    extends:
      file: kafka-compose.yml
      service: zookeeper

networks:
  backend:
    driver: bridge