services:
  postgres:
    extends:
      file: ./infrastructure/mongo/infra-compose.yml
      service: infrastructure

  keycloak:
    extends:
      file: keycloak-compose.yml
      service: keycloak

  kafka:
    extends:   
      file: kafka-compose.yml
      service: kafka

  zookeeper:
    extends:
      file: kafka-compose.yml
      service: zookeeper

networks:
  backend:
    driver: bridge
    

#C:\Users\imeda\IdeaProjects\droovo-backend
#docker-compose -f infrastructure/mongo/infra-compose.yml -f keycloak-compose.yml -f kafka-compose.yml up --build