server:
  port: 8088
  servlet:
    context-path: /

spring:
  application:
    name: gatewayservice

  cloud:
    gateway:
      routes:
        - id: usermessagingservice
          uri: http://localhost:8081
          predicates:
            - Path=/droovo/userservice/api/**
          filters:
            - StripPrefix=3  # strip /droovo/userservice/api

        - id: rideservice
          uri: http://localhost:8080
          predicates:
            - Path=/droovo/rideservices/api/**
          filters:
            - StripPrefix=3  # strip /droovo/rideservices/api
